# Generated by Django 4.2.4 on 2023-08-29 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weather', models.CharField(max_length=1000, verbose_name='Weather')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('date', models.DateField(verbose_name='Date')),
            ],
        ),
    ]
